/**
 * 
 */
package com.digows.blank.domain.entity.funcionario;

/**
 * @author lucas
 *
 */
public enum CursosEspecificos
{
	CRECHE,
	PRE_ESCOLA,
	ANOS_INICIAIS_ENSINO_FUNDAMENTAL,
	ANOS_FINAIS_ENSINO_FUNDAMENTAL,
	ENSINO_MEDIO,
	EDUCACAO_JOVENS_ADULTOS,
	EDICACAO_ESPECIAL,
	EDUCACAO_INDIGENA,
	EDUCACAO_CAMPO,
	EDUCACAO_AMBIENTAL,
	EDUCACAO_DIREITOS_HUMANOS,
	GENERO_DIVERSIDADE_SEXUAL,
	DIREITOS_CRIANCA_ADOLECENTE,
	RELACOES_ETNIRACIAIS,
	OUTROS,
	NENHUM
	
}
